FROM python:3.11.9-slim

WORKDIR /src

COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

COPY . /src

EXPOSE 5000

CMD ["streamlit","run", "Image_Retrieval.py","--server.port=5000", "--server.address=0.0.0.0"]